settings:
  title: 'Status Page'
  url: 'https://status.mxyz.tk' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: muxinxy-homepage # unique identifier
    name: muxinxy.com
    description: 'Homepage' # default=empty
    url: 'https://www.muxinxy.com' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: muxinxy-blog
    name: blog.muxinxy.com
    description: 'Blog' # default=empty
    url: 'https://blog.muxinxy.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: ai-chat
    name: AI Chat
    url: 'https://lines.zeabur.app/chat'
    method: GET
    expectStatus: 200

  - id: google-mirrors
    name: Google Mirrors
    url: 'https://lines.zeabur.app/google'
    method: GET
    expectStatus: 200
    
  - id: yesplay-music
    name: Yesplay Music
    url: 'https://y.mxyz.tk'
    method: GET
    expectStatus: 200

  - id: muxin-movies
    name: Movies & Series Website Release Page
    url: 'https://url.zeabur.app'
    method: GET
    expectStatus: 200

  - id: muxinxy-nav
    name: OneNav Website Navigation
    url: 'https://nav.muxinxy.com'
    method: GET
    expectStatus: 200

  - id: onedrive-list
    name: OneDrive List
    url: 'https://o.mxyz.tk'
    method: GET
    expectStatus: 200

  - id: github-proxy
    name: Github Files Proxy
    url: 'https://gh.mxyz.tk'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true

  - id: alist
    name: AList
    url: 'https://a.mxyz.tk'
    method: GET
    expectStatus: 200

  - id: telegraph-image
    name: Telegraph Image Bed
    url: 'https://img.mxy.hz.cz'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true

  - id: yourls
    name: Yourls Short URL
    url: 'https://mxyz.tk'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true

  - id: myapi
    name: AI API
    url: 'https://myapi.999875.xyz'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true

  - id: openwebui
    name: OpenWebUI
    url: 'https://open-webui.mxyz.tk'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true

  - id: xiaoya
    name: Xiaoya AList
    url: 'https://xy.mxyz.tk'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true
